// Code generated by protoc-gen-go.
// source: raft.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	raft.proto

It has these top-level messages:
	VoteRequest
	VoteResponse
	HeartbeatRequest
	Response
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VoteRequest struct {
	Term      uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Candidate string `protobuf:"bytes,2,opt,name=candidate" json:"candidate,omitempty"`
}

func (m *VoteRequest) Reset()                    { *m = VoteRequest{} }
func (m *VoteRequest) String() string            { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()               {}
func (*VoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VoteResponse struct {
	Term    uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Granted bool   `protobuf:"varint,2,opt,name=granted" json:"granted,omitempty"`
}

func (m *VoteResponse) Reset()                    { *m = VoteResponse{} }
func (m *VoteResponse) String() string            { return proto.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()               {}
func (*VoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HeartbeatRequest struct {
	Term   uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Leader string `protobuf:"bytes,2,opt,name=leader" json:"leader,omitempty"`
}

func (m *HeartbeatRequest) Reset()                    { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()               {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Response struct {
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*VoteRequest)(nil), "protocol.VoteRequest")
	proto.RegisterType((*VoteResponse)(nil), "protocol.VoteResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "protocol.HeartbeatRequest")
	proto.RegisterType((*Response)(nil), "protocol.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Raft service

type RaftClient interface {
	SendVoteRequest(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*Response, error)
	SendVoteResponse(ctx context.Context, in *VoteResponse, opts ...grpc.CallOption) (*Response, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Response, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) SendVoteRequest(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protocol.raft/SendVoteRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) SendVoteResponse(ctx context.Context, in *VoteResponse, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protocol.raft/SendVoteResponse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protocol.raft/Heartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Raft service

type RaftServer interface {
	SendVoteRequest(context.Context, *VoteRequest) (*Response, error)
	SendVoteResponse(context.Context, *VoteResponse) (*Response, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*Response, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_SendVoteRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).SendVoteRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.raft/SendVoteRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).SendVoteRequest(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_SendVoteResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).SendVoteResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.raft/SendVoteResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).SendVoteResponse(ctx, req.(*VoteResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.raft/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendVoteRequest",
			Handler:    _Raft_SendVoteRequest_Handler,
		},
		{
			MethodName: "SendVoteResponse",
			Handler:    _Raft_SendVoteResponse_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Raft_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x8d, 0x94, 0xb5, 0x1d, 0x05, 0x97, 0x01, 0x97, 0xb2, 0x78, 0x58, 0x72, 0xda, 0x53,
	0x0f, 0x7a, 0xd5, 0xd5, 0xa3, 0xe7, 0x08, 0xde, 0xd3, 0x66, 0x14, 0xa1, 0x26, 0x35, 0x1d, 0x9f,
	0xd1, 0xd7, 0x12, 0xd3, 0xc6, 0x94, 0x52, 0xf7, 0x94, 0xcc, 0x4f, 0xfe, 0x2f, 0xf3, 0x01, 0x78,
	0xfd, 0xca, 0x55, 0xe7, 0x1d, 0x3b, 0xcc, 0xc3, 0xd1, 0xb8, 0x56, 0x3e, 0xc0, 0xf9, 0x8b, 0x63,
	0x52, 0xf4, 0xf9, 0x45, 0x3d, 0x23, 0x42, 0xc6, 0xe4, 0x3f, 0x4a, 0xb1, 0x13, 0xfb, 0x4c, 0x85,
	0x3b, 0x5e, 0x43, 0xd1, 0x68, 0x6b, 0xde, 0x8d, 0x66, 0x2a, 0x4f, 0x77, 0x62, 0x5f, 0xa8, 0x14,
	0xc8, 0x3b, 0xb8, 0x18, 0x00, 0x7d, 0xe7, 0x6c, 0x4f, 0x8b, 0x84, 0x12, 0xce, 0xde, 0xbc, 0xb6,
	0x4c, 0x26, 0xf4, 0x73, 0x15, 0x47, 0x79, 0x80, 0xf5, 0x13, 0x69, 0xcf, 0x35, 0x69, 0x3e, 0xb6,
	0xc3, 0x06, 0x56, 0x2d, 0x69, 0x43, 0x7e, 0x5c, 0x60, 0x9c, 0x24, 0x40, 0x1e, 0x7f, 0xbe, 0xf9,
	0x16, 0x90, 0xfd, 0x3a, 0xe2, 0x01, 0x2e, 0x9f, 0xc9, 0x9a, 0xa9, 0xd7, 0x55, 0x15, 0x8d, 0xab,
	0x49, 0xbc, 0xc5, 0x14, 0x47, 0x8c, 0x3c, 0xc1, 0x47, 0x58, 0xa7, 0xfe, 0xa8, 0xb5, 0x99, 0x03,
	0x86, 0xfc, 0x1f, 0xc2, 0x3d, 0x14, 0x7f, 0x5a, 0xb8, 0x4d, 0x4f, 0xe6, 0xae, 0xcb, 0xf5, 0x7a,
	0x15, 0xc2, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xf4, 0x7d, 0x2f, 0xb3, 0x01, 0x00,
	0x00,
}
